name: Android Build ## Name of the workflow

on:
  workflow_dispatch: # To trigger manual build
  push:
    branches:
      - main

jobs:
  android-build:
    name: Android Build
    runs-on: ubuntu-latest # Using ubuntu latest version

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Set up JDK environment
        uses: actions/setup-java@v4
        with:
          distribution: "zulu"
          java-version: "17"

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - name: Restore node_modules from cache
        uses: actions/cache@v3
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install dependencies
        run: cd packages/app && yarn install

      # Debug step, remove later!!
      - name: List modules
        run: echo "AFTER INSTALL" && ls -la | grep rtn

      ## Configure cache for gradle to reduce build time
      - name: Cache Gradle Wrapper
        uses: actions/cache@v3
        with:
          path: ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-wrapper-${{ hashFiles('gradle/wrapper/gradle-wrapper.properties') }}

      - name: Cache Gradle Dependencies
        uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-caches-${{ hashFiles('gradle/wrapper/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-cache-

      - name: Make Gradle Executable
        # run: cd android && chmod +x ./gradle
        run: cd packages/app/android && chmod +x ./gradlew

      - name: Generate APK
        run: |
          cd packages/app/android && ./gradlew assembleRelease --no-daemon

      ## Sign generated APK
      - name: Sign APK
        id: sign_app
        uses: r0adkll/sign-android-release@v1
        with:
          releaseDirectory: packages/app/android/app/build/outputs/apk/release
          signingKeyBase64: ${{ secrets.ANDROID_SIGNING_KEY }}
          alias: ${{ secrets.ANDROID_ALIAS }}
          keyStorePassword: ${{ secrets.ANDROID_KEY_STORE_PASSWORD }}
          keyPassword: ${{ secrets.ANDROID_KEY_PASSWORD }}
